# Generated by Django 4.0.4 on 2022-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
